server:
  port: 8000
spring:
  application:
    name: shop-product
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://10.10.10.10:3306/gmall_product?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: 10.10.10.10
    port: 6379
    database: 2
    timeout: 1800000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 5
        max-active: 20
        max-wait: -1
  rabbitmq:
    host: 10.10.10.10
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.10.10:8848


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:com/gmall/product/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#FastDFS
fileServer:
  url: http://10.10.10.10/